Drop triggers loop fix (#252)
1) Postgres 16.1 throws an error:

```
NOTICE:  schema "grestv0" already exists, skipping
NOTICE:  web_anon exists, skipping...
NOTICE:  authenticator exists, skipping...
NOTICE:  role "authenticator" has already been granted membership in role "web_anon" by role "postgres"
NOTICE:  table "genesis" does not exist, skipping
NOTICE:  No fuctions found in schema grest
ERROR:  syntax error at or near "FOR"
LINE 1: FOR r IN (SELECT trigger_name, event_object_table FROM infor...
        ^
Exiting...
```